version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2
    commands:
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Commands...
  build:
    commands:
      - echo Running bundle exec rubocop...
      - echo bundle exec rubocop
      - echo Building the Rails API app...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
