version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2.2
    commands:
      - gem install bundler
  pre_build:
    commands:
      - echo "Installing gem dependencies..."
      - bundle install
  build:
    commands:
      - echo "Running bundle exec rubocop..."
      - bundle exec rubocop
      - echo "Running tests..."
      # Add your build commands here
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
