version: 0.2

phases:
  install:
    commands:
      - gem install bundler -v '2.5.6'
      - bundle install
  pre_build:
    commands:
      - echo Commands...
  build:
    commands:
      - echo Running bundle exec rubocop...
      - bundle exec rubocop
      - echo Building the Rails API app...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
