version: 0.2

phases:
  install:
    commands:
      # Ensure rbenv is installed correctly
      - |
        if [ ! -d "$HOME/.rbenv" ]; then
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        else
          echo "rbenv already installed"
        fi
      - |
        if [ ! -d "$HOME/.rbenv/plugins/ruby-build" ]; then
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        else
          echo "ruby-build already installed"
        fi
      - export PATH="$HOME/.rbenv/bin:$PATH"
      - eval "$(rbenv init -)"
      - |
        if rbenv versions | grep -q "3.3.0"; then
          echo "Ruby 3.3.0 already installed"
        else
          rbenv install 3.3.0
        fi
      - rbenv global 3.3.0
      - rbenv rehash
      - ruby -v
      - gem install bundler
  pre_build:
    commands:
      - echo "Installing gem dependencies..."
      - bundle install
  build:
    commands:
      - echo "Running bundle exec rubocop..."
      - bundle exec rubocop
      - echo "Running tests..."
      # Add your build commands here
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
