version: 0.2

phases:
  install:
    commands:
      # Ensure rbenv is installed correctly
      - |
        if [ ! -d "$HOME/.rbenv" ]; then
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        else
          echo "rbenv already installed"
        fi
      - |
        if [ ! -d "$HOME/.rbenv/plugins/ruby-build" ]; then
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        else
          echo "ruby-build already installed"
        fi
      - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      - echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      - source ~/.bashrc
      - rbenv install 3.3.0 --skip-existing
      - rbenv global 3.3.0
      - ruby -v
      - gem install bundler
  pre_build:
    commands:
      - echo "Installing gem dependencies..."
      - bundle install
  build:
    commands:
      - echo "Running tests..."
      # Add your build commands here
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
