---
openapi: 3.0.1
info:
  title: Navigate API V1
  version: v1
paths:
  "/api/v1/accounts":
    get:
      summary: Get Accounts
      tags:
      - Accounts
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Accounts List
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            id:
                              type: integer
                            uuid:
                              type: string
                            logo:
                              type: string
                            title:
                              type: string
                            created_at:
                              type: string
                            updated_at:
                              type: string
                          required:
                          - id
                          - uuid
                          - logo
                          - title
                          - deleted_at
                          - created_at
                          - updated_at
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/actions":
    get:
      summary: Get All Actions
      tags:
      - Actions
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Actions List
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            id:
                              type: string
                            title:
                              type: string
                            description:
                              type: string
                            action_kind:
                              type: string
                            deleted_at:
                              type: string
                            created_at:
                              type: string
                            updated_at:
                              type: string
                          required:
                          - id
                          - title
                          - description
                          - action_kind
                          - deleted_at
                          - created_at
                          - updated_at
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/activities":
    get:
      summary: Get Activities
      tags:
      - Activities
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Activity List
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    deleted_at:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    activity_actions:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        description:
                          type: string
                        order:
                          type: integer
                        details:
                          type: object
                        action_kind:
                          type: string
                        deleted_at:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                      required:
                      - id
                      - title
                      - description
                      - order
                      - details
                      - action_kind
                      - deleted_at
                      - created_at
                      - updated_at
                  required:
                  - id
                  - title
                  - description
                  - deleted_at
                  - created_at
                  - updated_at
                  - activity_actions
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
    post:
      summary: Create Activity
      tags:
      - Activities
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Activity Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  message:
                    type: string
                required:
                - id
                - message
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                required:
                - errors
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    activity_actions_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          details:
                            type: object
                          order:
                            type: integer
                          nav_action_id:
                            type: integer
              required:
              - activity
  "/api/v1/activities/{id}":
    get:
      summary: Get Activity
      tags:
      - Activities
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Activity Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  deleted_at:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  activity_actions:
                    type: object
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                      description:
                        type: string
                      order:
                        type: integer
                      details:
                        type: object
                      action_kind:
                        type: string
                      deleted_at:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - title
                    - description
                    - order
                    - details
                    - action_kind
                    - deleted_at
                    - created_at
                    - updated_at
                required:
                - id
                - title
                - description
                - deleted_at
                - created_at
                - updated_at
                - activity_actions
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/assessments":
    post:
      summary: Create Assessment
      tags:
      - Assessments
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Assessment Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  message:
                    type: string
                required:
                - id
                - message
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                required:
                - errors
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                assessment:
                  type: object
                  properties:
                    title:
                      type: string
                    account_id:
                      type: string
                    form_data:
                      type: object
                  required:
                  - title
                  - account_id
                  - form_data
              required:
              - assessment
  "/api/v1/assessments/{assessment_id}":
    get:
      summary: Get Assessment
      tags:
      - Assessments
      security:
      - bearerAuth: []
      parameters:
      - name: assessment_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Assessment Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                          form_data:
                            type: object
                          account:
                            type: object
                            properties:
                              id:
                                type: integer
                              title:
                                type: string
                          deleted_at:
                            type: string
                          created_at:
                            type: string
                          updated_at:
                            type: string
                        required:
                        - id
                        - title
                        - form_data
                        - account
                        - deleted_at
                        - created_at
                        - updated_at
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/employees/session":
    post:
      summary: Create an Employee Session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                      refresh_token:
                        type: string
                      token_expires_in:
                        type: integer
                    required:
                    - access_token
                    - refresh_token
                    - token_expires_in
                required:
                - data
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                employee:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - employee
    get:
      summary: Get Current Logged In Employee
      tags:
      - Sessions
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Logged In Employee Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      attributes:
                        type: object
                        properties:
                          id:
                            type: string
                          email:
                            type: string
                          first_name:
                            type: string
                          last_name:
                            type: string
                          company:
                            type: object
                            properties:
                              id:
                                type: string
                              title:
                                type: string
                              logo:
                                type: string
                              created_at:
                                type: string
                              updated_at:
                                type: string
                            required:
                            - id
                            - title
                            - logo
                            - created_at
                            - updated_at
                        required:
                        - id
                        - email
                        - first_name
                        - last_name
                        - cognito_username
                    required:
                    - data
        '401':
          description: Failed to Get User Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
