---
openapi: 3.0.1
info:
  title: Navigate API V1
  version: v1
paths:
  "/api/v1/actions":
    post:
      summary: Create Action
      tags:
      - Actions
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Action data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                required:
                - errors
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action_payload:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    action_kind:
                      type: string
                    details:
                      type: object
                  required:
                  - title
                  - description
                  - details
              required:
              - action
  "/api/v1/action_types":
    get:
      summary: Get Action Types
      tags:
      - Actions
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Action Types List
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                            description:
                              type: string
                            action_kind:
                              type: string
                            deleted_at:
                              type: string
                            created_at:
                              type: string
                            updated_at:
                              type: string
                          required:
                          - id
                          - title
                          - description
                          - action_kind
                          - created_at
                          - updated_at
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/employees/session":
    post:
      summary: Create an Employee Session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                      refresh_token:
                        type: string
                      token_expires_in:
                        type: integer
                    required:
                    - access_token
                    - refresh_token
                    - token_expires_in
                required:
                - data
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                employee:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - employee
    get:
      summary: Get Current Logged In Employee
      tags:
      - Sessions
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Logged In Employee Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      attributes:
                        type: object
                        properties:
                          id:
                            type: string
                          email:
                            type: string
                          first_name:
                            type: string
                          last_name:
                            type: string
                          company:
                            type: object
                            properties:
                              id:
                                type: string
                              title:
                                type: string
                              logo:
                                type: string
                              created_at:
                                type: string
                              updated_at:
                                type: string
                            required:
                            - id
                            - title
                            - logo
                            - created_at
                            - updated_at
                        required:
                        - id
                        - email
                        - first_name
                        - last_name
                        - cognito_username
                    required:
                    - data
        '401':
          description: Failed to Get User Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
